name: Make HTML-Table
on:
  workflow_run:
    workflows: [Update files]
    types: [completed]

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: update-out
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: Run bibliography_convert.py
      run: python bibliography_convert.py
    - name: Commit the changes to update_out
        run: |
          date > out/auto_gen_date_bib.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch
          git status
          git pull
          git add out\milet-bibliography-html-tablerows.txt
          git status
          git commit -m "auto-update html table"
          git push