name: Run Python Scripts
on:
  workflow_run:
    workflows: [Update files]
    types: [completed]

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  Python:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: update-out

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          cache: 'pip' # caching pip dependencies
      
      - name: Install python dependencies 
        run: pip install -r requirements.txt

      - name: Run bibliography_convert.py
        run: python bibliography_convert.py

      - name: Clean BibTeX and BibLaTeX files
        run: |
          python clean_bibtex.py
          python clean_biblatex.py
        
      - name: Commit the changes to update_out
        run: |
          date > out/auto_gen_date_bib.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git status
          git commit -m "auto-update html table and clean bib files"
          git push