name: Build Bibliography PDFs
on:
  push:
    branches:
      - workflow

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Github Action for LaTeX
        continue-on-error: true
        uses: xu-cheng/latex-action@v2
        with: 
          root_file: |
            tex/milet-bibliographie-by-author-pdf.tex
            tex/milet-bibliographie-by-year-pdf.tex
            tex/milet-bibliographie-by-tag-pdf.tex
            tex/milet-bibliographie-summary.tex
          work_in_root_file_dir: true
          continue_on_error: true
          args: --extra-mem-top=10000000

      - name: Upload files
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: |
            tex/*.pdf
            tex/*.log

          