name: Build Bibliography PDFs
on:
  workflow_run:
    workflows: [Update files]
    types: [completed]

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: update-out
      
      - name: Github Action for LaTeX
        continue-on-error: true
        uses: xu-cheng/latex-action@v2
        with: 
          compiler: latexmk
          args: -pdf -auxdir=logs/ -outdir=../out/pdf/
          work_in_root_file_dir: true
          continue_on_error: true
          root_file: |
            tex/milet-bibliographie-by-author-pdf.tex
            tex/milet-bibliographie-by-year-pdf.tex
            tex/milet-bibliographie-by-tag-pdf.tex
            tex/milet-bibliographie-summary.tex

      - name: Commit and push changes
        run: |
          date > out/auto_gen_date_pdf.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch
          git status
          git pull
          git add out/pdf/.
          git add out/auto_gen_date_pdf.txt
          git status
          git commit -m "auto-update pdfs"
          git push

      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: tex/logs/*.log

          