name: Build Bibliography PDFs
on:
  pull_request:
    types: [closed]

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Github Action for LaTeX
        continue-on-error: true
        uses: xu-cheng/latex-action@v2
        with: 
          compiler: latexmk
          args: -pdf -auxdir=logs/ -outdir=../out/pdf/
          work_in_root_file_dir: true
          continue_on_error: true
          root_file: |
            tex/milet-bibliographie-by-author-pdf.tex
            tex/milet-bibliographie-by-year-pdf.tex
            tex/milet-bibliographie-by-tag-pdf.tex
            tex/milet-bibliographie-summary.tex

      - name: add pdf directory and move files
        run: |
          date > out/auto_gen_date_pdf.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add *.pdf
          git add out/auto_gen_date_pdf.txt
          git status
          git commit -m "update pdfs [skip actions]"
          git push

      - name: Upload files
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: tex/logs/*.log

          