name: Build Bibliography PDFs
on:
  workflow_run:
    workflows: [Run Python Scripts]
    types: [completed]

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  Build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: update-out
      
      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@v3
        with: 
          compiler: latexmk
          args: -pdf -auxdir=logs/ -outdir=../out/pdf/
          work_in_root_file_dir: true
          latexmk_use_xelatex: true
          root_file: |
            tex/milet-bibliographie-by-author-pdf.tex
            tex/milet-bibliographie-by-year-pdf.tex
            tex/milet-bibliographie-by-tag-pdf.tex
            tex/milet-bibliographie-summary.tex

      - name: Commit and push changes
        run: |
          date > out/auto_gen_date_pdf.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add out/pdf/.
          git add out/auto_gen_date_pdf.txt
          git status
          git commit -m "auto-update pdfs"
          git push

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: tex/logs/*.log

          