name: Build Bibliography PDFs
on:
  pull_request:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@v2
        with: 
          root_file: tex/milet-bibliographie-summary.tex
          work_in_root_file_dir: true
          continue_on_error: true

      - name: Upload files
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: |
            tex/*.pdf
            tex/*.log

          