name: Build Bibliography
on:
  push:
    branches:
      - workflow

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
      - uses: r-lib/actions/setup-pandoc@v2
      
      - name: test
        run: source("build-bib.R")
        shell: Rscript {0}

      - name: Upload file
        uses: actions/upload-artifact@v3
        with:
          name: file
          path: test.html

          