name: Update files
on:
  push:
    branches:
      - workflow

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  tex-figures:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Install Packages
        uses: r-lib/actions/setup-renv@v2

      - name: Make files 
        run: Rscript -e 'source("build-bib.R", echo = TRUE)'
      
      - name: Commit the changes to update_out
        run: |
          date > out/auto_gen_date_bib.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git status
          git add .
          git status
          git commit -m "auto-update csv, tex files and figures"
          git push -d origin update-out
          git push origin workflow:update-out 

      - name: Pull Request for Update
        run: gh pr create -B workflow -H update-out --title 'Merge automated changes from update_out into main [skip actions]' --body 'Created by Github action ${{ github.workflow	}}'
