name: Update files
on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  tex-figures:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Install Packages
        uses: r-lib/actions/setup-renv@v2

      - name: Make files and commit the changes to update_out
        run: |
          Rscript -e 'source("build-bib.R")'
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git status
          git commit -m "update tex files and figures"
          git push origin main:update-out 

      - name: Pull Request for Update
        run: gh pr create -B main -H update-out --title 'Merge automated changes from update_out into main' --body 'Created by Github action ${{ github.action }}'
