name: Bibliography
on:
  push:
    branches:
      - workflow

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
      
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install Packages
        run: Rscript -e 'source("load_packages.R")'

      - name: Build tex files
        run: Rscript -e 'source("build-bib.R")'

      - name: Upload file
        uses: actions/upload-artifact@v3
        with:
          name: file
          path: test.html

          